# Generated by Django 5.0.2 on 2024-03-23 19:09

import SecFileSharingApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecFileSharingApp', '0002_rename_group_name_file_group_alter_file_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=SecFileSharingApp.models.file_upload_to),
        ),
    ]
