# Generated by Django 5.0.2 on 2024-04-21 12:20

import SecFileSharingApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecFileSharingApp', '0005_file_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=SecFileSharingApp.models.file_upload_to),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
