# Generated by Django 5.0.2 on 2024-04-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecFileSharingApp', '0006_alter_file_file_alter_file_file_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_data',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='public_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
