# Generated by Django 5.0.2 on 2024-04-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecFileSharingApp', '0007_remove_file_file_data_alter_appuser_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='encrypted_symmetric_key',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='encrypted_symmetric_key',
            field=models.BinaryField(),
        ),
    ]
