# Generated by Django 5.0.2 on 2024-06-01 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecFileSharingApp', '0010_alter_groupmember_unique_together'),
    ]

    operations = [
    ]
