# Generated by Django 5.0.2 on 2024-07-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecFileSharingApp', '0011_auto_20240602_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='signature',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
