# Generated by Django 5.0.2 on 2024-08-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecFileSharingApp', '0012_file_signature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
